-- 코드를 입력하세요
SELECT F.FLAVOR FROM FIRST_HALF AS F JOIN ( 
SELECT FLAVOR, SUM(TOTAL_ORDER) AS JS FROM JULY GROUP BY FLAVOR 
    ) AS J ON J.FLAVOR = F.FLAVOR
ORDER BY (J.JS + F.TOTAL_ORDER) DESC LIMIT 3;