-- 코드를 입력하세요
SELECT AP.APNT_NO, P.PT_NAME, AP.PT_NO, AP.MCDP_CD, D.DR_NAME, AP.APNT_YMD FROM APPOINTMENT AS AP JOIN DOCTOR AS D ON D.DR_ID = AP.MDDR_ID JOIN PATIENT AS P ON P.PT_NO = AP.PT_NO
WHERE DATE_FORMAT(APNT_YMD,'%Y-%m-%d') = '2022-04-13' and APNT_CNCL_YN = "N"
ORDER BY AP.APNT_YMD ASC